# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^helm/charts/[^/]+/templates/.*
      - id: check-toml
      - id: pretty-format-json
        args: [--autofix]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        exclude: ^helm/charts/[^/]+/templates/.*
