apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - httproute.yaml
helmCharts:
  - name: rustfs
    repo: https://charts.rustfs.com
    version: 1.0.0-rc.3
    releaseName: rustfs
    namespace: rustfs
    valuesFile: values.yaml
