apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-global-config
  namespace: platform
  annotations:
    argocd.argoproj.io/ignore-default-links: "true"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/wesleyfebarretos/argocd-applications.git
        revision: main
        directories:
          - path: tenants/*/*/overlays/*
        values:
          namespace: "{{ index .path.segments 1}}-{{ index .path.segments 2}}-{{ index .path.segments 4}}"
          tenant: "{{ index .path.segments 1 }}"
          project: "{{ index .path.segments 2 }}"
          environment: "{{ .path.basename }}"
  template:
    metadata:
      name: "{{ .values.namespace }}-config"
      labels:
        app.kubernetes.io/name: "{{ .values.namespace }}-config"
        tenant: "{{ .values.tenant }}"
        project: "{{ .values.project }}"
    spec:
      project: platform
      sources:
        - repoURL: https://github.com/wesleyfebarretos/argocd-control-plane.git
          path: "helm/charts/project-template"
          targetRevision: main
          helm:
            valueFiles:
              - "$values/projects/{{ .values.project }}/values.yaml"
              - "$values/tenants/{{ .values.tenant }}/{{ .values.project}}/{{ .values.environment }}/values.yaml"
            ignoreMissingValueFiles: true
            parameters:
              - name: namespace
                value: "{{ .values.namespace }}"
              - name: tenant
                value: "{{ .values.tenant }}"
              - name: project
                value: "{{ .values.project }}"
              - name: environment
                value: "{{ .values.environment }}"
        - repoURL: https://github.com/wesleyfebarretos/argocd-control-plane.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .values.namespace }}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
