# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/applicationset-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            wave: "-10"
          - name: sealed-secrets
            namespace: sealed-secrets
            wave: "-10"
          - name: external-secrets
            namespace: external-secrets
            wave: "1"
          - name: envoy-gateway
            namespace: envoy-gateway-system
            wave: "1"
          - name: envoy-proxy
            namespace: envoy-gateway-system
            wave: "2"
          - name: gateway
            namespace: envoy-gateway-system
            wave: "3"
          - name: metrics-server
            namespace: kube-system
            wave: "4"
          - name: argocd
            namespace: argocd
            wave: "4"
          - name: vault
            namespace: vault
            wave: "4"
          - name: rustfs
            namespace: rustfs
            wave: "5"
          - name: cloudnative-pg
            namespace: cloudnative-pg
            wave: "5"
          - name: kargo
            namespace: kargo
            wave: "1"
  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        kargo.akuity.io/authorized-stage: platform:prod
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
      labels:
        app.kubernetes.io/part-of: platform
        environment: prod
        team: platform
    spec:
      project: platform
      source:
        repoURL: https://github.com/wesleyfebarretos/argocd-control-plane.git
        targetRevision: stage/prod
        path: "{{ .name }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
