{{- $appProject := .Values.appProject | default dict }}

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "project-template.namespace" . }}
  namespace: argocd
spec:
  description: "Project for {{ include "project-template.namespace" . }} namespace"
  sourceRepos:
    - https://github.com/wesleyfebarretos/argocd-applications.git
  sourceNamespaces:
    - {{ include "project-template.namespace" . }}
  destinations:
    - namespace: {{ include "project-template.namespace" . }}
      server: https://kubernetes.default.svc
  {{- with $appProject.clusterResourceWhitelist }}
  clusterResourceWhitelist: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $appProject.namespaceResourceWhitelist }}
  namespaceResourceWhitelist: {{ toYaml . | nindent 4 }}
  {{- end }}
  orphanedResources:
    warn: false
