apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "project-template.namespace" . }}
  namespace: {{ include "project-template.namespace" . }}
  # annotations:
  #   link.argocd.argoproj.io/config: https://argocd.internal/applications/platform/{{ include "project-template.namespace" . }}-config
spec:
  project: {{ include "project-template.namespace" . }}
  source:
    repoURL: https://github.com/wesleyfebarretos/argocd-applications.git
    path: tenants/{{ include "project-template.tenant" . }}/{{ include "project-template.project" . }}/overlays/{{ include "project-template.environment" . }}
    targetRevision: main
  destination:
    namespace: {{ include "project-template.namespace" . }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - ApplyOutOfSyncOnly=true
