apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: {{ include "project-template.namespace" . }}
spec:
  hard:
    pods: {{ .Values.resourceQuota.pods | quote }}
    requests.cpu: {{ .Values.resourceQuota.requests.cpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requests.memory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limits.cpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limits.memory | quote }}
