apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform team project with restricted repo and namespaces
  sourceRepos:
    - https://github.com/wesleyfebarretos/argocd-control-plane.git
  sourceNamespaces:
    - argocd
    - platform
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
  roles:
    - name: admin
      description: Full access within platform project
      policies:
        - 'p, proj:platform:admin, applications, *, platform/*, allow'
      groups:
        - wesleyfebarretos@gmail.com
