apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kargo-tls
spec:
  secretName: kargo-tls
  issuerRef:
    kind: ClusterIssuer
    name: platform-selfsigned
  dnsNames:
    - kargo.internal
  privateKey:
    algorithm: ECDSA
    size: 256
---
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: allow-platform-gateway-tls
  namespace: kargo
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Secret
      name: kargo-tls
