apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterConfig
metadata:
  name: cluster
spec:
  webhookReceivers:
    - name: github-webhook-receiver
      github:
        secretRef:
          name: github-webhook-secrett
