apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: render-platform-manifests
spec:
  image: ubuntu:24.04
  command:
    - bash
    - ${{ config.srcPath }}/platform/kargo/render-manifests.sh
  env:
    - name: HOME
      value: /tmp/home
    - name: SRC_PATH
      value: ${{ config.srcPath }}
    - name: OUT_PATH
      value: ${{ config.outPath }}
  output:
    source:
      type: Stdout
      format: Text
    transform:
      lines: split(trimSuffix(output, "\n"), "\n")
  defaultTimeout: 30m
  defaultErrorThreshold: 2
  resources:
    requests:
      memory: 1Gi
      cpu: "1"
    limits:
      memory: 4Gi
      cpu: "2"
