apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealedsecrets.yaml
  - project.yaml
  - warehouse.yaml
  - promotiontask.yaml
  - stages.yaml
  - clusterconfig.yaml
  - routes.yaml
helmCharts:
  - name: kargo
    repo: oci://ghcr.io/akuity/kargo-charts
    version: 1.11.4
    namespace: kargo
    releaseName: kargo
    includeCRDs: true
    valuesFile: values.yaml
