apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: platform
annotations:
  kargo.akuity.io/keep-namespace: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: platform
  namespace: platform
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
