apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: render-platform-manifests
  namespace: platform
spec:
  vars:
    - name: repoURL
      value: https://github.com/wesleyfebarretos/argocd-control-plane.git
    - name: targetBranch
      value: stage/${{ ctx.stage }}
    - name: srcPath
      value: ./src
    - name: outPath
      value: ./out
    - name: openPR
      value: "false"
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.repoURL }}
        checkout:
          - commit: ${{ commitFrom(vars.repoURL).ID }}
            path: ${{ vars.srcPath }}
          - branch: ${{ vars.targetBranch }}
            create: true
            path: ${{ vars.outPath }}
    - uses: git-clear
      config:
        path: ${{ vars.outPath }}
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/argocd
        outPath: ${{ vars.outPath }}/argocd/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/cert-manager
        outPath: ${{ vars.outPath }}/cert-manager/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/cloudnative-pg
        outPath: ${{ vars.outPath }}/cloudnative-pg/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/envoy-gateway
        outPath: ${{ vars.outPath }}/envoy-gateway/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/envoy-proxy
        outPath: ${{ vars.outPath }}/envoy-proxy/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/external-secrets
        outPath: ${{ vars.outPath }}/external-secrets/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/gateway
        outPath: ${{ vars.outPath }}/gateway/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/kargo
        outPath: ${{ vars.outPath }}/kargo/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/metrics-server
        outPath: ${{ vars.outPath }}/metrics-server/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/rustfs
        outPath: ${{ vars.outPath }}/rustfs/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/sealed-secrets
        outPath: ${{ vars.outPath }}/sealed-secrets/manifests.yaml
    - uses: kustomize-build
      config:
        path: ${{ vars.srcPath }}/platform/vault
        outPath: ${{ vars.outPath }}/vault/manifests.yaml
    - uses: git-commit
      as: commit
      config:
        path: ${{ vars.outPath }}
        message: Render platform manifests from ${{ commitFrom(vars.repoURL).ID }}
    - if: ${{ vars.openPR != 'true' }}
      uses: git-push
      as: push
      config:
        path: ${{ vars.outPath }}
    - if: ${{ vars.openPR == 'true' }}
      uses: git-push
      as: push-pr
      config:
        path: ${{ vars.outPath }}
        generateTargetBranch: true
    - if: ${{ vars.openPR == 'true' }}
      uses: git-open-pr
      as: open-pr
      config:
        repoURL: ${{ vars.repoURL }}
        sourceBranch: ${{ task.outputs['push-pr'].branch }}
        targetBranch: ${{ vars.targetBranch }}
        title: Render platform manifests for ${{ ctx.stage }}
    - if: ${{ vars.openPR == 'true' && status('task-1::open-pr') != 'Skipped' }}
      uses: git-wait-for-pr
      as: wait-for-pr
      config:
        repoURL: ${{ vars.repoURL }}
        prNumber: ${{ task.outputs['open-pr'].pr.id }}
    - if: ${{ len(vars.apps) > 0 && (vars.openPR != 'true' || status('task-1::open-pr') == 'Succeeded') }}
      uses: argocd-update
      config:
        apps:
          - selector:
              matchLabels:
                environment: ${{ ctx.stage }}
                team: platform
            sources:
              - repoURL: ${{ vars.repoURL }}
                desiredRevision: ${{ if vars.openPR == 'true' { task.outputs['wait-for-pr'].commit } else { task.outputs.push.commit } }}
