apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: platform
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: argocd-control-plane
      sources:
        direct: true
        autoPromotionOptions:
          selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      steps:
        - task:
            name: render-platform-manifests
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: platform
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: argocd-control-plane
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: render-platform-manifests
            vars:
              - name: openPR
                value: "true"
