appProject:
  clusterResourceWhitelist:
    - group: ''
      kind: "Namespace"
  namespaceResourceWhitelist:
    # argoproj.io/v1alpha1
    - group: 'argoproj.io'
      kind: Application
    - group: 'argoproj.io'
      kind: ApplicationSet
    # core/v1
    - group: ''
      kind: Service
    - group: ''
      kind: Secret
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: Pod
    # apps/v1
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: apps
      kind: ReplicaSet
    # autoscaling/v2
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    # networking.k8s.io/v1
    - group: networking.k8s.io
      kind: Ingress
    # gateway.networking.k8s.io/v1
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
